# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Program Files\Python 2.7\baser\programs\release\base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_baseConverter(object):
    def setupUi(self, baseConverter):
        baseConverter.setObjectName(_fromUtf8("baseConverter"))
        baseConverter.resize(561, 509)
        self.verticalLayout = QtGui.QVBoxLayout(baseConverter)
        self.verticalLayout.setMargin(1)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.topOverviewLabel = QtGui.QLabel(baseConverter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topOverviewLabel.sizePolicy().hasHeightForWidth())
        self.topOverviewLabel.setSizePolicy(sizePolicy)
        self.topOverviewLabel.setMinimumSize(QtCore.QSize(0, 22))
        self.topOverviewLabel.setMaximumSize(QtCore.QSize(16777215, 22))
        self.topOverviewLabel.setText(_fromUtf8(""))
        self.topOverviewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.topOverviewLabel.setObjectName(_fromUtf8("topOverviewLabel"))
        self.verticalLayout.addWidget(self.topOverviewLabel)
        self.splitter = QtGui.QSplitter(baseConverter)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.leftVertical = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.leftVertical.setObjectName(_fromUtf8("leftVertical"))
        self.leftHorizontal = QtGui.QHBoxLayout()
        self.leftHorizontal.setObjectName(_fromUtf8("leftHorizontal"))
        self.leftTopLabel = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftTopLabel.sizePolicy().hasHeightForWidth())
        self.leftTopLabel.setSizePolicy(sizePolicy)
        self.leftTopLabel.setMinimumSize(QtCore.QSize(70, 22))
        self.leftTopLabel.setMaximumSize(QtCore.QSize(16777215, 22))
        self.leftTopLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leftTopLabel.setObjectName(_fromUtf8("leftTopLabel"))
        self.leftHorizontal.addWidget(self.leftTopLabel)
        self.leftRealBaseInput = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftRealBaseInput.sizePolicy().hasHeightForWidth())
        self.leftRealBaseInput.setSizePolicy(sizePolicy)
        self.leftRealBaseInput.setMinimumSize(QtCore.QSize(30, 22))
        self.leftRealBaseInput.setMaximumSize(QtCore.QSize(80, 22))
        self.leftRealBaseInput.setWrapping(True)
        self.leftRealBaseInput.setFrame(True)
        self.leftRealBaseInput.setAlignment(QtCore.Qt.AlignCenter)
        self.leftRealBaseInput.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.leftRealBaseInput.setSuffix(_fromUtf8(""))
        self.leftRealBaseInput.setDecimals(0)
        self.leftRealBaseInput.setMinimum(-2048.0)
        self.leftRealBaseInput.setMaximum(2048.0)
        self.leftRealBaseInput.setProperty("value", 10.0)
        self.leftRealBaseInput.setObjectName(_fromUtf8("leftRealBaseInput"))
        self.leftHorizontal.addWidget(self.leftRealBaseInput)
        self.leftImagBaseInput = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftImagBaseInput.sizePolicy().hasHeightForWidth())
        self.leftImagBaseInput.setSizePolicy(sizePolicy)
        self.leftImagBaseInput.setMinimumSize(QtCore.QSize(30, 22))
        self.leftImagBaseInput.setMaximumSize(QtCore.QSize(80, 22))
        self.leftImagBaseInput.setWrapping(True)
        self.leftImagBaseInput.setFrame(True)
        self.leftImagBaseInput.setAlignment(QtCore.Qt.AlignCenter)
        self.leftImagBaseInput.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.leftImagBaseInput.setDecimals(0)
        self.leftImagBaseInput.setMinimum(-2048.0)
        self.leftImagBaseInput.setMaximum(2048.0)
        self.leftImagBaseInput.setProperty("value", 0.0)
        self.leftImagBaseInput.setObjectName(_fromUtf8("leftImagBaseInput"))
        self.leftHorizontal.addWidget(self.leftImagBaseInput)
        self.leftVertical.addLayout(self.leftHorizontal)
        self.leftRealTextInput = QtGui.QTextEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftRealTextInput.sizePolicy().hasHeightForWidth())
        self.leftRealTextInput.setSizePolicy(sizePolicy)
        self.leftRealTextInput.setMinimumSize(QtCore.QSize(100, 100))
        self.leftRealTextInput.setObjectName(_fromUtf8("leftRealTextInput"))
        self.leftVertical.addWidget(self.leftRealTextInput)
        self.leftImagTextInput = QtGui.QTextEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftImagTextInput.sizePolicy().hasHeightForWidth())
        self.leftImagTextInput.setSizePolicy(sizePolicy)
        self.leftImagTextInput.setMinimumSize(QtCore.QSize(100, 100))
        self.leftImagTextInput.setObjectName(_fromUtf8("leftImagTextInput"))
        self.leftVertical.addWidget(self.leftImagTextInput)
        self.leftBottomLabel = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBottomLabel.sizePolicy().hasHeightForWidth())
        self.leftBottomLabel.setSizePolicy(sizePolicy)
        self.leftBottomLabel.setMinimumSize(QtCore.QSize(100, 22))
        self.leftBottomLabel.setMaximumSize(QtCore.QSize(16777215, 22))
        self.leftBottomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.leftBottomLabel.setObjectName(_fromUtf8("leftBottomLabel"))
        self.leftVertical.addWidget(self.leftBottomLabel)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.centerVertical = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.centerVertical.setObjectName(_fromUtf8("centerVertical"))
        self.centerTopLabel = QtGui.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerTopLabel.sizePolicy().hasHeightForWidth())
        self.centerTopLabel.setSizePolicy(sizePolicy)
        self.centerTopLabel.setMinimumSize(QtCore.QSize(0, 28))
        self.centerTopLabel.setMaximumSize(QtCore.QSize(16777215, 28))
        self.centerTopLabel.setText(_fromUtf8(""))
        self.centerTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.centerTopLabel.setObjectName(_fromUtf8("centerTopLabel"))
        self.centerVertical.addWidget(self.centerTopLabel)
        self.centerHortizontal01 = QtGui.QHBoxLayout()
        self.centerHortizontal01.setObjectName(_fromUtf8("centerHortizontal01"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal01.addItem(spacerItem)
        self.rebaseButton = QtGui.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rebaseButton.sizePolicy().hasHeightForWidth())
        self.rebaseButton.setSizePolicy(sizePolicy)
        self.rebaseButton.setMinimumSize(QtCore.QSize(75, 22))
        self.rebaseButton.setMaximumSize(QtCore.QSize(75, 22))
        self.rebaseButton.setCheckable(True)
        self.rebaseButton.setObjectName(_fromUtf8("rebaseButton"))
        self.centerHortizontal01.addWidget(self.rebaseButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal01.addItem(spacerItem1)
        self.centerVertical.addLayout(self.centerHortizontal01)
        self.centerHortizontal02 = QtGui.QHBoxLayout()
        self.centerHortizontal02.setObjectName(_fromUtf8("centerHortizontal02"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal02.addItem(spacerItem2)
        self.invertButton = QtGui.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invertButton.sizePolicy().hasHeightForWidth())
        self.invertButton.setSizePolicy(sizePolicy)
        self.invertButton.setMinimumSize(QtCore.QSize(75, 22))
        self.invertButton.setMaximumSize(QtCore.QSize(75, 22))
        self.invertButton.setCheckable(True)
        self.invertButton.setObjectName(_fromUtf8("invertButton"))
        self.centerHortizontal02.addWidget(self.invertButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal02.addItem(spacerItem3)
        self.centerVertical.addLayout(self.centerHortizontal02)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.centerVertical.addItem(spacerItem4)
        self.centerHortizontal03 = QtGui.QHBoxLayout()
        self.centerHortizontal03.setObjectName(_fromUtf8("centerHortizontal03"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal03.addItem(spacerItem5)
        self.classVertical = QtGui.QVBoxLayout()
        self.classVertical.setObjectName(_fromUtf8("classVertical"))
        self.classGroupBox = QtGui.QGroupBox(self.verticalLayoutWidget_3)
        self.classGroupBox.setEnabled(True)
        self.classGroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.classGroupBox.setAutoFillBackground(False)
        self.classGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.classGroupBox.setFlat(False)
        self.classGroupBox.setObjectName(_fromUtf8("classGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.classGroupBox)
        self.verticalLayout_2.setContentsMargins(3, 0, 3, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.useRealCB = QtGui.QCheckBox(self.classGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useRealCB.sizePolicy().hasHeightForWidth())
        self.useRealCB.setSizePolicy(sizePolicy)
        self.useRealCB.setMinimumSize(QtCore.QSize(80, 20))
        self.useRealCB.setMaximumSize(QtCore.QSize(16777215, 20))
        self.useRealCB.setCheckable(True)
        self.useRealCB.setChecked(True)
        self.useRealCB.setAutoExclusive(True)
        self.useRealCB.setObjectName(_fromUtf8("useRealCB"))
        self.verticalLayout_2.addWidget(self.useRealCB)
        self.useImagCB = QtGui.QCheckBox(self.classGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useImagCB.sizePolicy().hasHeightForWidth())
        self.useImagCB.setSizePolicy(sizePolicy)
        self.useImagCB.setMinimumSize(QtCore.QSize(80, 20))
        self.useImagCB.setMaximumSize(QtCore.QSize(16777215, 20))
        self.useImagCB.setAutoExclusive(True)
        self.useImagCB.setObjectName(_fromUtf8("useImagCB"))
        self.verticalLayout_2.addWidget(self.useImagCB)
        self.useCmpxCB = QtGui.QCheckBox(self.classGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useCmpxCB.sizePolicy().hasHeightForWidth())
        self.useCmpxCB.setSizePolicy(sizePolicy)
        self.useCmpxCB.setMinimumSize(QtCore.QSize(80, 20))
        self.useCmpxCB.setMaximumSize(QtCore.QSize(16777215, 20))
        self.useCmpxCB.setAutoExclusive(True)
        self.useCmpxCB.setObjectName(_fromUtf8("useCmpxCB"))
        self.verticalLayout_2.addWidget(self.useCmpxCB)
        self.classVertical.addWidget(self.classGroupBox)
        self.forceIntegerCB = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forceIntegerCB.sizePolicy().hasHeightForWidth())
        self.forceIntegerCB.setSizePolicy(sizePolicy)
        self.forceIntegerCB.setMinimumSize(QtCore.QSize(80, 18))
        self.forceIntegerCB.setMaximumSize(QtCore.QSize(16777215, 18))
        self.forceIntegerCB.setChecked(True)
        self.forceIntegerCB.setObjectName(_fromUtf8("forceIntegerCB"))
        self.classVertical.addWidget(self.forceIntegerCB)
        self.centerHortizontal03.addLayout(self.classVertical)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal03.addItem(spacerItem6)
        self.centerVertical.addLayout(self.centerHortizontal03)
        self.centerHortizontal04 = QtGui.QHBoxLayout()
        self.centerHortizontal04.setObjectName(_fromUtf8("centerHortizontal04"))
        spacerItem7 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal04.addItem(spacerItem7)
        self.sgnInput = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sgnInput.sizePolicy().hasHeightForWidth())
        self.sgnInput.setSizePolicy(sizePolicy)
        self.sgnInput.setMinimumSize(QtCore.QSize(20, 20))
        self.sgnInput.setMaximumSize(QtCore.QSize(20, 20))
        self.sgnInput.setMaxLength(1)
        self.sgnInput.setAlignment(QtCore.Qt.AlignCenter)
        self.sgnInput.setObjectName(_fromUtf8("sgnInput"))
        self.centerHortizontal04.addWidget(self.sgnInput)
        self.precInput = QtGui.QSpinBox(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.precInput.sizePolicy().hasHeightForWidth())
        self.precInput.setSizePolicy(sizePolicy)
        self.precInput.setMinimumSize(QtCore.QSize(40, 20))
        self.precInput.setMaximumSize(QtCore.QSize(40, 20))
        self.precInput.setAlignment(QtCore.Qt.AlignCenter)
        self.precInput.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.precInput.setAccelerated(True)
        self.precInput.setMinimum(30)
        self.precInput.setMaximum(25000)
        self.precInput.setSingleStep(10)
        self.precInput.setProperty("value", 30)
        self.precInput.setObjectName(_fromUtf8("precInput"))
        self.centerHortizontal04.addWidget(self.precInput)
        self.sepInput = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.sepInput.sizePolicy().hasHeightForWidth())
        self.sepInput.setSizePolicy(sizePolicy)
        self.sepInput.setMinimumSize(QtCore.QSize(20, 20))
        self.sepInput.setMaximumSize(QtCore.QSize(20, 20))
        self.sepInput.setMaxLength(1)
        self.sepInput.setAlignment(QtCore.Qt.AlignCenter)
        self.sepInput.setObjectName(_fromUtf8("sepInput"))
        self.centerHortizontal04.addWidget(self.sepInput)
        spacerItem8 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal04.addItem(spacerItem8)
        self.centerVertical.addLayout(self.centerHortizontal04)
        self.centerHortizontal05 = QtGui.QHBoxLayout()
        self.centerHortizontal05.setObjectName(_fromUtf8("centerHortizontal05"))
        spacerItem9 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal05.addItem(spacerItem9)
        self.orderButton = QtGui.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderButton.sizePolicy().hasHeightForWidth())
        self.orderButton.setSizePolicy(sizePolicy)
        self.orderButton.setMinimumSize(QtCore.QSize(90, 18))
        self.orderButton.setMaximumSize(QtCore.QSize(90, 18))
        self.orderButton.setObjectName(_fromUtf8("orderButton"))
        self.centerHortizontal05.addWidget(self.orderButton)
        spacerItem10 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal05.addItem(spacerItem10)
        self.centerVertical.addLayout(self.centerHortizontal05)
        self.centerHortizontal06 = QtGui.QHBoxLayout()
        self.centerHortizontal06.setObjectName(_fromUtf8("centerHortizontal06"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal06.addItem(spacerItem11)
        self.optionButton = QtGui.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionButton.sizePolicy().hasHeightForWidth())
        self.optionButton.setSizePolicy(sizePolicy)
        self.optionButton.setMinimumSize(QtCore.QSize(55, 22))
        self.optionButton.setMaximumSize(QtCore.QSize(55, 22))
        self.optionButton.setCheckable(True)
        self.optionButton.setObjectName(_fromUtf8("optionButton"))
        self.centerHortizontal06.addWidget(self.optionButton)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.centerHortizontal06.addItem(spacerItem12)
        self.centerVertical.addLayout(self.centerHortizontal06)
        self.centerBottomLabel = QtGui.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerBottomLabel.sizePolicy().hasHeightForWidth())
        self.centerBottomLabel.setSizePolicy(sizePolicy)
        self.centerBottomLabel.setMinimumSize(QtCore.QSize(0, 28))
        self.centerBottomLabel.setMaximumSize(QtCore.QSize(16777215, 28))
        self.centerBottomLabel.setText(_fromUtf8(""))
        self.centerBottomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.centerBottomLabel.setObjectName(_fromUtf8("centerBottomLabel"))
        self.centerVertical.addWidget(self.centerBottomLabel)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.rightVertical = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.rightVertical.setObjectName(_fromUtf8("rightVertical"))
        self.rightHorizontal = QtGui.QHBoxLayout()
        self.rightHorizontal.setObjectName(_fromUtf8("rightHorizontal"))
        self.rightTopLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightTopLabel.sizePolicy().hasHeightForWidth())
        self.rightTopLabel.setSizePolicy(sizePolicy)
        self.rightTopLabel.setMinimumSize(QtCore.QSize(70, 22))
        self.rightTopLabel.setMaximumSize(QtCore.QSize(16777215, 22))
        self.rightTopLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rightTopLabel.setObjectName(_fromUtf8("rightTopLabel"))
        self.rightHorizontal.addWidget(self.rightTopLabel)
        self.rightRealBaseInput = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightRealBaseInput.sizePolicy().hasHeightForWidth())
        self.rightRealBaseInput.setSizePolicy(sizePolicy)
        self.rightRealBaseInput.setMinimumSize(QtCore.QSize(30, 22))
        self.rightRealBaseInput.setMaximumSize(QtCore.QSize(80, 22))
        self.rightRealBaseInput.setWrapping(True)
        self.rightRealBaseInput.setFrame(True)
        self.rightRealBaseInput.setAlignment(QtCore.Qt.AlignCenter)
        self.rightRealBaseInput.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.rightRealBaseInput.setDecimals(0)
        self.rightRealBaseInput.setMinimum(-2048.0)
        self.rightRealBaseInput.setMaximum(2048.0)
        self.rightRealBaseInput.setProperty("value", 10.0)
        self.rightRealBaseInput.setObjectName(_fromUtf8("rightRealBaseInput"))
        self.rightHorizontal.addWidget(self.rightRealBaseInput)
        self.rightImagBaseInput = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightImagBaseInput.sizePolicy().hasHeightForWidth())
        self.rightImagBaseInput.setSizePolicy(sizePolicy)
        self.rightImagBaseInput.setMinimumSize(QtCore.QSize(30, 22))
        self.rightImagBaseInput.setMaximumSize(QtCore.QSize(80, 22))
        self.rightImagBaseInput.setWrapping(True)
        self.rightImagBaseInput.setFrame(True)
        self.rightImagBaseInput.setAlignment(QtCore.Qt.AlignCenter)
        self.rightImagBaseInput.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.rightImagBaseInput.setDecimals(0)
        self.rightImagBaseInput.setMinimum(-2048.0)
        self.rightImagBaseInput.setMaximum(2048.0)
        self.rightImagBaseInput.setProperty("value", 0.0)
        self.rightImagBaseInput.setObjectName(_fromUtf8("rightImagBaseInput"))
        self.rightHorizontal.addWidget(self.rightImagBaseInput)
        self.rightVertical.addLayout(self.rightHorizontal)
        self.rightRealTextInput = QtGui.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightRealTextInput.sizePolicy().hasHeightForWidth())
        self.rightRealTextInput.setSizePolicy(sizePolicy)
        self.rightRealTextInput.setMinimumSize(QtCore.QSize(100, 100))
        self.rightRealTextInput.setObjectName(_fromUtf8("rightRealTextInput"))
        self.rightVertical.addWidget(self.rightRealTextInput)
        self.rightImagTextInput = QtGui.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightImagTextInput.sizePolicy().hasHeightForWidth())
        self.rightImagTextInput.setSizePolicy(sizePolicy)
        self.rightImagTextInput.setMinimumSize(QtCore.QSize(100, 100))
        self.rightImagTextInput.setObjectName(_fromUtf8("rightImagTextInput"))
        self.rightVertical.addWidget(self.rightImagTextInput)
        self.rightBottomLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightBottomLabel.sizePolicy().hasHeightForWidth())
        self.rightBottomLabel.setSizePolicy(sizePolicy)
        self.rightBottomLabel.setMinimumSize(QtCore.QSize(100, 22))
        self.rightBottomLabel.setMaximumSize(QtCore.QSize(16777215, 22))
        self.rightBottomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rightBottomLabel.setObjectName(_fromUtf8("rightBottomLabel"))
        self.rightVertical.addWidget(self.rightBottomLabel)
        self.verticalLayout.addWidget(self.splitter)
        self.bottomOverviewLabel = QtGui.QLabel(baseConverter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomOverviewLabel.sizePolicy().hasHeightForWidth())
        self.bottomOverviewLabel.setSizePolicy(sizePolicy)
        self.bottomOverviewLabel.setMinimumSize(QtCore.QSize(0, 22))
        self.bottomOverviewLabel.setMaximumSize(QtCore.QSize(16777215, 22))
        self.bottomOverviewLabel.setText(_fromUtf8(""))
        self.bottomOverviewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bottomOverviewLabel.setObjectName(_fromUtf8("bottomOverviewLabel"))
        self.verticalLayout.addWidget(self.bottomOverviewLabel)

        self.retranslateUi(baseConverter)
        QtCore.QMetaObject.connectSlotsByName(baseConverter)

    def retranslateUi(self, baseConverter):
        baseConverter.setWindowTitle(_translate("baseConverter", "Base Converter", None))
        self.leftTopLabel.setText(_translate("baseConverter", "Base 10", None))
        self.leftImagBaseInput.setSuffix(_translate("baseConverter", "i", None))
        self.leftRealTextInput.setToolTip(_translate("baseConverter", "Real part", None))
        self.leftImagTextInput.setToolTip(_translate("baseConverter", "Imaginary part", None))
        self.leftBottomLabel.setText(_translate("baseConverter", "Input", None))
        self.rebaseButton.setToolTip(_translate("baseConverter", "Convert", None))
        self.rebaseButton.setText(_translate("baseConverter", "Rebase >>", None))
        self.invertButton.setToolTip(_translate("baseConverter", "Flips the conversion windows", None))
        self.invertButton.setText(_translate("baseConverter", "Invert", None))
        self.classGroupBox.setToolTip(_translate("baseConverter", "Number type for base inputs", None))
        self.classGroupBox.setTitle(_translate("baseConverter", "Class", None))
        self.useRealCB.setToolTip(_translate("baseConverter", "use real values for bases", None))
        self.useRealCB.setText(_translate("baseConverter", "Real", None))
        self.useImagCB.setToolTip(_translate("baseConverter", "use imaginary values for bases", None))
        self.useImagCB.setText(_translate("baseConverter", "Imaginary", None))
        self.useCmpxCB.setToolTip(_translate("baseConverter", "use complex values for bases", None))
        self.useCmpxCB.setText(_translate("baseConverter", "Complex", None))
        self.forceIntegerCB.setToolTip(_translate("baseConverter", "Simplify base input selection\n"
" - restricts base input to just integer (or Gaussian integer) values", None))
        self.forceIntegerCB.setText(_translate("baseConverter", "Integers Only", None))
        self.sgnInput.setToolTip(_translate("baseConverter", "Negative sign", None))
        self.sgnInput.setText(_translate("baseConverter", "-", None))
        self.sgnInput.setPlaceholderText(_translate("baseConverter", "-", None))
        self.precInput.setToolTip(_translate("baseConverter", "Precision\n"
"the # of digits after the radix point\n"
"that are correct in base two", None))
        self.precInput.setSpecialValueText(_translate("baseConverter", "30", None))
        self.sepInput.setToolTip(_translate("baseConverter", "Fractional seperator\n"
"(Radix)", None))
        self.sepInput.setText(_translate("baseConverter", ".", None))
        self.sepInput.setPlaceholderText(_translate("baseConverter", ".", None))
        self.orderButton.setToolTip(_translate("baseConverter", "Edit the order of the character digit set", None))
        self.orderButton.setText(_translate("baseConverter", "Character order", None))
        self.optionButton.setToolTip(_translate("baseConverter", "Options", None))
        self.optionButton.setText(_translate("baseConverter", "Options", None))
        self.rightTopLabel.setText(_translate("baseConverter", "Base 10", None))
        self.rightImagBaseInput.setSuffix(_translate("baseConverter", "i", None))
        self.rightRealTextInput.setToolTip(_translate("baseConverter", "Real part", None))
        self.rightImagTextInput.setToolTip(_translate("baseConverter", "Imaginary part", None))
        self.rightBottomLabel.setText(_translate("baseConverter", "Output", None))

