# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Program Files\Python 2.7\baser\programs\release\charEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_digitOrderEditor(object):
    def setupUi(self, digitOrderEditor):
        digitOrderEditor.setObjectName(_fromUtf8("digitOrderEditor"))
        digitOrderEditor.resize(451, 383)
        self.horizontalLayout = QtGui.QHBoxLayout(digitOrderEditor)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sidebarLayout = QtGui.QVBoxLayout()
        self.sidebarLayout.setObjectName(_fromUtf8("sidebarLayout"))
        self.posiLabel = QtGui.QLabel(digitOrderEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posiLabel.sizePolicy().hasHeightForWidth())
        self.posiLabel.setSizePolicy(sizePolicy)
        self.posiLabel.setMinimumSize(QtCore.QSize(50, 18))
        self.posiLabel.setMaximumSize(QtCore.QSize(50, 18))
        self.posiLabel.setText(_fromUtf8(""))
        self.posiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.posiLabel.setObjectName(_fromUtf8("posiLabel"))
        self.sidebarLayout.addWidget(self.posiLabel)
        self.charLabel = QtGui.QLabel(digitOrderEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charLabel.sizePolicy().hasHeightForWidth())
        self.charLabel.setSizePolicy(sizePolicy)
        self.charLabel.setMinimumSize(QtCore.QSize(50, 50))
        self.charLabel.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.charLabel.setFont(font)
        self.charLabel.setText(_fromUtf8(""))
        self.charLabel.setScaledContents(True)
        self.charLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.charLabel.setObjectName(_fromUtf8("charLabel"))
        self.sidebarLayout.addWidget(self.charLabel)
        self.reprLabel = QtGui.QLabel(digitOrderEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reprLabel.sizePolicy().hasHeightForWidth())
        self.reprLabel.setSizePolicy(sizePolicy)
        self.reprLabel.setMinimumSize(QtCore.QSize(50, 18))
        self.reprLabel.setMaximumSize(QtCore.QSize(50, 18))
        self.reprLabel.setText(_fromUtf8(""))
        self.reprLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.reprLabel.setObjectName(_fromUtf8("reprLabel"))
        self.sidebarLayout.addWidget(self.reprLabel)
        self.shuffleButton = QtGui.QPushButton(digitOrderEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shuffleButton.sizePolicy().hasHeightForWidth())
        self.shuffleButton.setSizePolicy(sizePolicy)
        self.shuffleButton.setMinimumSize(QtCore.QSize(50, 22))
        self.shuffleButton.setMaximumSize(QtCore.QSize(50, 22))
        self.shuffleButton.setObjectName(_fromUtf8("shuffleButton"))
        self.sidebarLayout.addWidget(self.shuffleButton)
        self.defaultButton = QtGui.QPushButton(digitOrderEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultButton.sizePolicy().hasHeightForWidth())
        self.defaultButton.setSizePolicy(sizePolicy)
        self.defaultButton.setMinimumSize(QtCore.QSize(50, 22))
        self.defaultButton.setMaximumSize(QtCore.QSize(50, 22))
        self.defaultButton.setObjectName(_fromUtf8("defaultButton"))
        self.sidebarLayout.addWidget(self.defaultButton)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.sidebarLayout.addItem(spacerItem)
        self.closeButton = QtGui.QPushButton(digitOrderEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMinimumSize(QtCore.QSize(50, 40))
        self.closeButton.setMaximumSize(QtCore.QSize(50, 40))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.sidebarLayout.addWidget(self.closeButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.sidebarLayout.addItem(spacerItem1)
        self.devButtonsLayout = QtGui.QVBoxLayout()
        self.devButtonsLayout.setObjectName(_fromUtf8("devButtonsLayout"))
        self.devlayout_hz_1 = QtGui.QHBoxLayout()
        self.devlayout_hz_1.setSpacing(4)
        self.devlayout_hz_1.setObjectName(_fromUtf8("devlayout_hz_1"))
        self.numCol_input = QtGui.QSpinBox(digitOrderEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numCol_input.sizePolicy().hasHeightForWidth())
        self.numCol_input.setSizePolicy(sizePolicy)
        self.numCol_input.setMinimumSize(QtCore.QSize(23, 22))
        self.numCol_input.setMaximumSize(QtCore.QSize(20, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.numCol_input.setFont(font)
        self.numCol_input.setStatusTip(_fromUtf8(""))
        self.numCol_input.setFrame(True)
        self.numCol_input.setAlignment(QtCore.Qt.AlignCenter)
        self.numCol_input.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.numCol_input.setMinimum(1)
        self.numCol_input.setMaximum(128)
        self.numCol_input.setProperty("value", 30)
        self.numCol_input.setObjectName(_fromUtf8("numCol_input"))
        self.devlayout_hz_1.addWidget(self.numCol_input)
        self.itemSize_input = QtGui.QSpinBox(digitOrderEditor)
        self.itemSize_input.setMinimumSize(QtCore.QSize(23, 22))
        self.itemSize_input.setMaximumSize(QtCore.QSize(20, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.itemSize_input.setFont(font)
        self.itemSize_input.setAlignment(QtCore.Qt.AlignCenter)
        self.itemSize_input.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.itemSize_input.setMinimum(5)
        self.itemSize_input.setMaximum(120)
        self.itemSize_input.setSingleStep(5)
        self.itemSize_input.setProperty("value", 30)
        self.itemSize_input.setObjectName(_fromUtf8("itemSize_input"))
        self.devlayout_hz_1.addWidget(self.itemSize_input)
        self.devButtonsLayout.addLayout(self.devlayout_hz_1)
        self.updateTableButton = QtGui.QPushButton(digitOrderEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateTableButton.sizePolicy().hasHeightForWidth())
        self.updateTableButton.setSizePolicy(sizePolicy)
        self.updateTableButton.setMinimumSize(QtCore.QSize(50, 22))
        self.updateTableButton.setMaximumSize(QtCore.QSize(50, 22))
        self.updateTableButton.setObjectName(_fromUtf8("updateTableButton"))
        self.devButtonsLayout.addWidget(self.updateTableButton)
        self.maxChar_input = QtGui.QSpinBox(digitOrderEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxChar_input.sizePolicy().hasHeightForWidth())
        self.maxChar_input.setSizePolicy(sizePolicy)
        self.maxChar_input.setMinimumSize(QtCore.QSize(50, 22))
        self.maxChar_input.setMaximumSize(QtCore.QSize(50, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.maxChar_input.setFont(font)
        self.maxChar_input.setWrapping(True)
        self.maxChar_input.setAlignment(QtCore.Qt.AlignCenter)
        self.maxChar_input.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.maxChar_input.setMinimum(1)
        self.maxChar_input.setMaximum(1114111)
        self.maxChar_input.setProperty("value", 1114111)
        self.maxChar_input.setObjectName(_fromUtf8("maxChar_input"))
        self.devButtonsLayout.addWidget(self.maxChar_input)
        self.sidebarLayout.addLayout(self.devButtonsLayout)
        self.horizontalLayout.addLayout(self.sidebarLayout)
        self.charTableLayout = QtGui.QVBoxLayout()
        self.charTableLayout.setObjectName(_fromUtf8("charTableLayout"))
        self.charButtonsLayout = QtGui.QHBoxLayout()
        self.charButtonsLayout.setObjectName(_fromUtf8("charButtonsLayout"))
        self.exportButton = QtGui.QPushButton(digitOrderEditor)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.charButtonsLayout.addWidget(self.exportButton)
        self.infoLabel = QtGui.QLabel(digitOrderEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoLabel.sizePolicy().hasHeightForWidth())
        self.infoLabel.setSizePolicy(sizePolicy)
        self.infoLabel.setMinimumSize(QtCore.QSize(50, 20))
        self.infoLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.infoLabel.setText(_fromUtf8(""))
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName(_fromUtf8("infoLabel"))
        self.charButtonsLayout.addWidget(self.infoLabel)
        self.cancelButton = QtGui.QPushButton(digitOrderEditor)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.charButtonsLayout.addWidget(self.cancelButton)
        self.importButton = QtGui.QPushButton(digitOrderEditor)
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.charButtonsLayout.addWidget(self.importButton)
        self.charTableLayout.addLayout(self.charButtonsLayout)
        self.horizontalLayout.addLayout(self.charTableLayout)

        self.retranslateUi(digitOrderEditor)
        QtCore.QMetaObject.connectSlotsByName(digitOrderEditor)

    def retranslateUi(self, digitOrderEditor):
        digitOrderEditor.setWindowTitle(_translate("digitOrderEditor", "Digit Order Editor", None))
        digitOrderEditor.setWhatsThis(_translate("digitOrderEditor", "Digit Order Editor", None))
        self.posiLabel.setToolTip(_translate("digitOrderEditor", "Position", None))
        self.posiLabel.setWhatsThis(_translate("digitOrderEditor", "Position", None))
        self.charLabel.setToolTip(_translate("digitOrderEditor", "Character", None))
        self.charLabel.setWhatsThis(_translate("digitOrderEditor", "Character", None))
        self.reprLabel.setToolTip(_translate("digitOrderEditor", "Representation", None))
        self.reprLabel.setWhatsThis(_translate("digitOrderEditor", "Representation", None))
        self.shuffleButton.setToolTip(_translate("digitOrderEditor", "Randomizes the digit order", None))
        self.shuffleButton.setWhatsThis(_translate("digitOrderEditor", "Randomizes the digit order", None))
        self.shuffleButton.setText(_translate("digitOrderEditor", "Shuffle", None))
        self.defaultButton.setToolTip(_translate("digitOrderEditor", "Resets the digit order", None))
        self.defaultButton.setWhatsThis(_translate("digitOrderEditor", "Resets the digit order", None))
        self.defaultButton.setText(_translate("digitOrderEditor", "Default", None))
        self.closeButton.setToolTip(_translate("digitOrderEditor", "Saves the digit order and closes", None))
        self.closeButton.setWhatsThis(_translate("digitOrderEditor", "Saves the digit order and closes", None))
        self.closeButton.setText(_translate("digitOrderEditor", "Save &&\n"
"Close", None))
        self.numCol_input.setToolTip(_translate("digitOrderEditor", "Number of columns", None))
        self.numCol_input.setWhatsThis(_translate("digitOrderEditor", "Sets the number of columns in character display table", None))
        self.itemSize_input.setToolTip(_translate("digitOrderEditor", "Item size", None))
        self.itemSize_input.setWhatsThis(_translate("digitOrderEditor", "Sets the item size in character display table", None))
        self.updateTableButton.setToolTip(_translate("digitOrderEditor", "Update the character display table", None))
        self.updateTableButton.setWhatsThis(_translate("digitOrderEditor", "Updates the character display table", None))
        self.updateTableButton.setText(_translate("digitOrderEditor", "Update", None))
        self.maxChar_input.setToolTip(_translate("digitOrderEditor", "Maximum number of characters", None))
        self.maxChar_input.setWhatsThis(_translate("digitOrderEditor", "Sets the maximum number of characters to display", None))
        self.exportButton.setToolTip(_translate("digitOrderEditor", "Export the digit order for external rearranging", None))
        self.exportButton.setWhatsThis(_translate("digitOrderEditor", "Exports the digit order to a file", None))
        self.exportButton.setText(_translate("digitOrderEditor", "Export", None))
        self.infoLabel.setWhatsThis(_translate("digitOrderEditor", "infomation label", None))
        self.cancelButton.setToolTip(_translate("digitOrderEditor", "Cancel file import", None))
        self.cancelButton.setWhatsThis(_translate("digitOrderEditor", "Cancels file import", None))
        self.cancelButton.setText(_translate("digitOrderEditor", "Cancel", None))
        self.importButton.setToolTip(_translate("digitOrderEditor", "Import custom digit order", None))
        self.importButton.setWhatsThis(_translate("digitOrderEditor", "Imports a digit order from a file", None))
        self.importButton.setText(_translate("digitOrderEditor", "Import", None))

